library(data.table)
library(ggplot2)
library(gplots)
library(ComplexHeatmap)
library(BiocManager)
library(GSVA)
library(BiocParallel)
library(doParallel)
library(stringr)
library(circlize)
library(RColorBrewer)
library(ggpubr)
library(GSA)
library(Matrix)
library(extrafont)
library(Rtsne)
library(Polychrome)
library(R.utils)
library(igraph)
library(dnet)
library(AUCell)
library(doMC)
loadfonts()
registerDoParallel(20)
ht_opt$message = FALSE

setwd("/export/cse/rmall/Raghvendra/PT-AML2.0/")
source("scripts/all_patients_functions.R")

################################################################################
# Load FIMM-AML drug sensitivity scores for the 78 common drugs (long format)
# Columns: Sample_ID, Compound_ID, Chemical_compound, EC50, ..., DSS, sDSS
################################################################################
fimmaml_sens_df <- fread("Data/FIMM-AML/Drug_Sensitivity_Scores_Common.csv", header = TRUE)
fimmaml_sens_df <- as.data.frame(fimmaml_sens_df)

# Rename to canonical names used throughout
colnames(fimmaml_sens_df)[colnames(fimmaml_sens_df) == "Sample_ID"]         <- "sample_id"
colnames(fimmaml_sens_df)[colnames(fimmaml_sens_df) == "Chemical_compound"] <- "inhibitor"

fimmaml_drug_df <- fimmaml_sens_df[, c("sample_id", "inhibitor", "DSS", "sDSS")]
fimmaml_drug_df <- fimmaml_drug_df[complete.cases(fimmaml_drug_df), ]

unique_drugs    <- unique(fimmaml_drug_df$inhibitor)
unique_patients <- unique(fimmaml_drug_df$sample_id)
cat(sprintf("Unique drugs: %d | Unique samples: %d\n", length(unique_drugs), length(unique_patients)))

################################################################################
# Build drug-target table
# - fimmaml_drug_cids.csv  : FIMM_Name → BeatAML_Name (for the 78 mapped drugs)
# - Data/target_gene_info.csv : BeatAML drug properties including Targets column
################################################################################
drug_targets_df <- fread("Data/target_gene_info_overlapping_name_with_fimmaml.csv", header = TRUE)
drug_targets_df <- as.data.frame(drug_targets_df)

cids_df <- fread("Data/FIMM-AML/fimmaml_drug_cids.csv", header = TRUE)
cids_df <- as.data.frame(cids_df)
# Columns: Id, FIMM_Name, BeatAML_Name, Match_Type, cid

# Join: map each FIMM drug name to BeatAML name, then pull target info
drug_map <- merge(
  cids_df[, c("FIMM_Name", "BeatAML_Name", "cid")],
  drug_targets_df[, c("Name", "MolecularWeight", "CanonicalSMILES", "InChIKey", "XLogP", "Targets")],
  by.x = "BeatAML_Name", by.y = "Name", all.x = FALSE
)

# drug_map now has: BeatAML_Name, FIMM_Name, cid, MolecularWeight, ..., Targets
# Use FIMM_Name as the inhibitor key to match the sensitivity data
drug_info_rev <- drug_map[, c("FIMM_Name", "BeatAML_Name",
                               "MolecularWeight", "CanonicalSMILES",
                               "InChIKey", "XLogP", "Targets")]
colnames(drug_info_rev)[1] <- "inhibitor"

cat(sprintf("Drugs in response data:   %d\n", length(unique_drugs)))
cat(sprintf("Drugs with target info:   %d\n", sum(unique_drugs %in% drug_info_rev$inhibitor)))
cat(sprintf("Drugs without target info: %s\n",
    paste(setdiff(unique_drugs, drug_info_rev$inhibitor), collapse = ", ")))

################################################################################
# Merge drug info into long sensitivity table
################################################################################
fimmaml_drug_df_with_info <- merge(fimmaml_drug_df, drug_info_rev,
                                    by = "inhibitor", all = FALSE)
fimmaml_drug_df_with_info <- fimmaml_drug_df_with_info[
  complete.cases(fimmaml_drug_df_with_info), ]

# Primary key: inhibitor_sampleid
fimmaml_drug_df_with_info$primary_key <- paste0(
  fimmaml_drug_df_with_info$inhibitor, "_",
  fimmaml_drug_df_with_info$sample_id)

################################################################################
# Load FIMM-AML patient expression + pathway + cell-type feature matrix
# (generated by analyze_fimmaml_sequence_data.R)
################################################################################
fimmaml_patient_df <- fread("Data/FIMM-AML/FIMMAML_Set_with_Expr_PA_CTS.csv",
                              header = TRUE, sep = "\t")
fimmaml_patient_df <- as.data.frame(fimmaml_patient_df)

fimmaml_onco_patient_df <- fread("Data/FIMM-AML/FIMMAML_Set_with_Onco_Var_Expr_PA_CTS.csv",
                                   header = TRUE, sep = "\t")
fimmaml_onco_patient_df <- as.data.frame(fimmaml_onco_patient_df)

# Identify gene expression columns via the metadata file
fimmaml_meta_df    <- fread("Data/FIMM-AML/FIMMAML_Metadata.csv", header = TRUE)
fimmaml_meta_df    <- as.data.frame(fimmaml_meta_df)
fimmaml_gene_names <- fimmaml_meta_df$Column_Label[fimmaml_meta_df$Type == "Gene_Expr"]

# Keep only samples present in both expression and drug sensitivity data
rev_patient_ids <- intersect(fimmaml_patient_df$Sample_ID, unique_patients)
fimmaml_patient_df      <- fimmaml_patient_df[fimmaml_patient_df$Sample_ID %in% rev_patient_ids, ]
fimmaml_onco_patient_df <- fimmaml_onco_patient_df[fimmaml_onco_patient_df$Sample_ID %in% rev_patient_ids, ]
fimmaml_drug_df_with_info <- fimmaml_drug_df_with_info[
  fimmaml_drug_df_with_info$sample_id %in% rev_patient_ids, ]

cat(sprintf("Samples with both expression and drug data: %d\n", length(rev_patient_ids)))
cat(sprintf("Drug-sample pairs kept: %d\n", nrow(fimmaml_drug_df_with_info)))

################################################################################
# t-SNE on FIMM-AML oncogene+pathway+cell-type feature set
################################################################################
set.seed(123)

str_col_ids <- which(sapply(fimmaml_onco_patient_df, class) == "character")
na_col_ids  <- which(colSums(is.na(fimmaml_onco_patient_df)) > 0)
sd_col_ids  <- which(apply(fimmaml_onco_patient_df, 2, function(x) {
  xn <- suppressWarnings(as.numeric(x)); sd(xn, na.rm = TRUE) }) == 0)
excl_ids    <- union(union(str_col_ids, na_col_ids), sd_col_ids)
feat_df     <- fimmaml_onco_patient_df[, -excl_ids, drop = FALSE]

perp     <- min(5, floor((nrow(feat_df) - 1) / 3))
tsne_out <- Rtsne(X = feat_df, dims = 2, perplexity = perp,
                  pca_center = TRUE, pca_scale = TRUE, pca = TRUE)
tsne_df  <- as.data.frame(tsne_out[["Y"]])
colnames(tsne_df) <- c("Tsne1", "Tsne2")
tsne_df$Sample_ID <- fimmaml_onco_patient_df$Sample_ID

P28 <- createPalette(28, c("#ff0000", "#00ff00", "#0000ff"))
palette(P28)

g_tsne <- ggplot(data = tsne_df, aes(x = Tsne1, y = Tsne2)) +
  geom_point(size = 2, color = "#2166AC") + theme_bw() +
  xlab("T-SNE Dim1") + ylab("T-SNE Dim2") +
  theme(axis.text.x  = element_text(color = "grey20", size = 16, angle = 0,  hjust = .5, vjust = .5, face = "plain"),
        strip.text   = element_text(color = "white",  size = 20, angle = 0,  hjust = 0.5, vjust = 0.5, face = "plain"),
        axis.text.y  = element_text(color = "grey20", size = 16, angle = 0,  hjust = 1,  vjust = 0,  face = "plain"),
        axis.title.x = element_text(color = "grey20", size = 20, angle = 0,  hjust = .5, vjust = 0,  face = "plain"),
        axis.title.y = element_text(color = "grey20", size = 20, angle = 90, hjust = .5, vjust = .5, face = "plain"),
        legend.text  = element_text(color = "grey20", size = 18, angle = 0,  face = "plain"),
        title        = element_text(color = "grey20", size = 20, face = "plain"))
ggsave(filename = "Data/FIMM-AML/FIMMAML_Feature_Set_T-SNE_plot.pdf",
       plot = g_tsne, device = pdf(), height = 8, width = 8, units = "in")
dev.off()

################################################################################
# Load STRING PPI graph
################################################################################
string_ppi_df <- read.table("Data/String_PPI_Cutoff_0.7.csv", header = TRUE)
g_ppi   <- graph_from_edgelist(as.matrix(string_ppi_df[, c(1:2)]), directed = TRUE)
E(g_ppi)$weight <- string_ppi_df$combined_score
N_ppi   <- length(V(g_ppi))

unique_drugs_final <- unique(fimmaml_drug_df_with_info$inhibitor)

################################################################################
# Build drug seed matrix for Random Walk with Restart (RWR)
################################################################################
p0_matrix <- matrix(0, nrow = N_ppi, ncol = length(unique_drugs_final))
rownames(p0_matrix) <- V(g_ppi)$name
colnames(p0_matrix) <- unique_drugs_final

for (i in seq_along(unique_drugs_final)) {
  drug_name <- unique_drugs_final[i]
  targets   <- drug_info_rev[drug_info_rev$inhibitor == drug_name, ]$Targets
  targets   <- unlist(strsplit(targets, split = ";"))
  p0_vec    <- rep(0, N_ppi)
  names(p0_vec) <- V(g_ppi)$name
  p0_vec[names(p0_vec) %in% targets] <- 1
  p0_matrix[, i] <- p0_vec
}

# RWR stationary distribution
pinf_matrix <- sqrt(dRWR(g = g_ppi, normalise = "laplacian",
                          setSeeds = p0_matrix, restart = 0.5, multicores = 8))
rownames(pinf_matrix) <- V(g_ppi)$name
colnames(pinf_matrix) <- unique_drugs_final
pinf_matrix <- as.matrix(pinf_matrix)

################################################################################
# Build drug-patient affinity matrix (gene expression x RWR affinity)
################################################################################
all_genes_in_ppi     <- rownames(pinf_matrix)
all_genes_in_patient <- colnames(fimmaml_patient_df)[colnames(fimmaml_patient_df) %in% fimmaml_gene_names]
common_genes         <- intersect(all_genes_in_ppi, all_genes_in_patient)
cat(sprintf("Genes common to PPI and expression: %d\n", length(common_genes)))

revised_pinf_matrix <- t(pinf_matrix[common_genes, ])   # drugs x common_genes

revised_patient_expr_df <- fimmaml_patient_df[, common_genes, drop = FALSE]
rownames(revised_patient_expr_df) <- fimmaml_patient_df$Sample_ID

################################################################################
# Drug-patient affinity combinations matrix (common_genes x drug*sample)
################################################################################
drug_patient_affinity_combinations <- t(sapply(
  seq_along(common_genes),
  function(i) tcrossprod(revised_pinf_matrix[, i], revised_patient_expr_df[, i])
))
drug_patient_affinity_combinations_mat <- Matrix(drug_patient_affinity_combinations, sparse = TRUE)
rm(drug_patient_affinity_combinations)
gc()

all_drug_patient_combination <- as.data.frame(
  expand.grid(rownames(revised_pinf_matrix), rownames(revised_patient_expr_df))
)
all_drug_patient_combination <- paste0(all_drug_patient_combination$Var1, "_",
                                        all_drug_patient_combination$Var2)
colnames(drug_patient_affinity_combinations_mat) <- all_drug_patient_combination
rownames(drug_patient_affinity_combinations_mat) <- common_genes

################################################################################
# AUCell pathway enrichment on drug-patient affinity matrix
################################################################################
load("Data/Selected.pathways.3.4.RData")

N         <- ncol(drug_patient_affinity_combinations_mat)
blocks    <- min(50, N)
blocksize <- ceiling(N / blocks)
auc_scores_df <- NULL

for (i in seq_len(blocks)) {
  start <- (i - 1) * blocksize + 1
  end   <- min(i * blocksize, N)
  if (start > N) next
  ids   <- start:end
  patient_rankings_temp <- AUCell_buildRankings(
    exprMat   = as.matrix(drug_patient_affinity_combinations_mat[, ids]),
    nCores    = 8,
    plotStats = FALSE
  )
  temp_auc_scores <- AUCell_calcAUC(
    geneSets   = Selected.pathways,
    rankings   = patient_rankings_temp,
    nCores     = 8,
    normAUC    = TRUE,
    aucMaxRank = ceiling(0.5 * nrow(patient_rankings_temp))
  )
  auc_scores_df <- AUCell::cbind(auc_scores_df,
                                  temp_auc_scores@assays@data@listData$AUC)
  rm(temp_auc_scores, patient_rankings_temp)
  gc()
}

auc_scores_df <- t(auc_scores_df)
colnames(auc_scores_df) <- paste0("AUC_", names(Selected.pathways))

################################################################################
# Subset AUC scores to observed drug-patient combinations and merge with response
################################################################################
combinations_to_keep <- fimmaml_drug_df_with_info$primary_key

subset_auc_scores_df <- auc_scores_df[
  rownames(auc_scores_df) %in% combinations_to_keep, , drop = FALSE]
for (i in seq_len(ncol(subset_auc_scores_df))) {
  subset_auc_scores_df[, i] <- signif(subset_auc_scores_df[, i], digits = 3)
}
subset_auc_scores_df             <- as.data.frame(subset_auc_scores_df)
subset_auc_scores_df$primary_key <- rownames(subset_auc_scores_df)

fimmaml_drug_response_final <- merge(fimmaml_drug_df_with_info, subset_auc_scores_df,
                                      by = "primary_key", all = FALSE)

write.table(fimmaml_drug_response_final,
            file      = "Data/FIMM-AML/FIMMAML_Set_with_AUC.csv",
            row.names = FALSE, col.names = TRUE, quote = FALSE, sep = "\t")

cat(sprintf("Final drug-response rows saved: %d\n", nrow(fimmaml_drug_response_final)))
cat(sprintf("Unique drugs in final set:      %d\n", length(unique(fimmaml_drug_response_final$inhibitor))))
cat(sprintf("Unique samples in final set:    %d\n", length(unique(fimmaml_drug_response_final$sample_id))))
