# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.18.1
#   kernelspec:
#     display_name: BeatAML2.0
#     language: python
#     name: python3
# ---

# %% [markdown]
# # TabPFN Ablation Study - Summary
#
# Combines results from all four ablation scripts and generates comparison plots and tables.
#
# **Required result files** (generated by the experiment scripts):
# - `ablation_results_1group.pkl`
# - `ablation_results_2group.pkl`
# - `ablation_results_3group.pkl`
# - `ablation_results_4group_baseline.pkl`

# %%
import os
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

os.makedirs("../Results/tabpfn/ablation/", exist_ok=True)

# %% [markdown]
# ## Load All Ablation Results

# %%
result_files = {
    "1group": "../Results/tabpfn/ablation/ablation_results_1group.pkl",
    "2group": "../Results/tabpfn/ablation/ablation_results_2group.pkl",
    "3group": "../Results/tabpfn/ablation/ablation_results_3group.pkl",
    "4group_baseline": "../Results/tabpfn/ablation/ablation_results_4group_baseline.pkl",
}

all_results = {}
for label, path in result_files.items():
    with open(path, "rb") as f:
        results = pickle.load(f)
    print(f"Loaded {label}: {len(results)} experiments")
    all_results.update(results)

print(f"\nTotal experiments loaded: {len(all_results)}")

# %% [markdown]
# ## Full Summary Table

# %%
summary_data = []
for exp_name, result in all_results.items():
    m = result["metrics"]
    if exp_name == "baseline_all_features":
        combo_size = 4
        groups_used = "ALL"
    else:
        parts = exp_name.split("_", 2)
        combo_size = int(parts[1])
        groups_used = parts[2]

    summary_data.append({
        "Experiment": exp_name,
        "Combo_Size": combo_size,
        "Groups": groups_used,
        "N_Features": result["n_features"],
        "MAE": round(m[0], 3),
        "RMSE": round(m[1], 3),
        "R2": round(m[2], 3),
        "Pearson_R": round(m[3], 3),
        "Spearman_R": round(m[4], 3)
    })

summary_df = pd.DataFrame(summary_data).sort_values(["Combo_Size", "MAE"])
print(summary_df.to_string(index=False))

summary_df.to_csv("../Results/tabpfn/ablation/ablation_summary.csv", index=False)
print("\nSaved ablation_summary.csv")

# %% [markdown]
# ## Best Combination per Group Size

# %%
print("Best combination at each level (by MAE):\n")
best_rows = []
for k in sorted(summary_df["Combo_Size"].unique()):
    subset = summary_df[summary_df["Combo_Size"] == k]
    best = subset.iloc[0]
    best_rows.append(best)
    print(f"  {k}-group: {best['Groups']}")
    print(f"           MAE={best['MAE']}, RMSE={best['RMSE']}, R2={best['R2']}, "
          f"Pearson={best['Pearson_R']}, Spearman={best['Spearman_R']}")
    print()

best_df = pd.DataFrame(best_rows)
best_df.to_csv("../Results/tabpfn/ablation/ablation_best_per_size.csv", index=False)
print("Saved ablation_best_per_size.csv")

# %% [markdown]
# ## Comparison Plots - All Experiments

# %%
fig, axes = plt.subplots(1, 3, figsize=(18, max(8, len(summary_df) * 0.35)))
fig.set_dpi(150)
fig.set_facecolor("white")

color_map = {1: "coral", 2: "steelblue", 3: "mediumpurple", 4: "green"}
colors = [color_map.get(k, "gray") for k in summary_df["Combo_Size"]]

# MAE comparison
ax = axes[0]
ax.barh(summary_df["Experiment"], summary_df["MAE"], color=colors, alpha=0.8)
ax.set_xlabel("MAE (lower is better)")
ax.set_title("Mean Absolute Error")
ax.invert_yaxis()

# Pearson R comparison
ax = axes[1]
ax.barh(summary_df["Experiment"], summary_df["Pearson_R"], color=colors, alpha=0.8)
ax.set_xlabel("Pearson R (higher is better)")
ax.set_title("Pearson Correlation")
ax.invert_yaxis()

# R2 comparison
ax = axes[2]
ax.barh(summary_df["Experiment"], summary_df["R2"], color=colors, alpha=0.8)
ax.set_xlabel("R-squared (higher is better)")
ax.set_title("R-Squared")
ax.invert_yaxis()

plt.tight_layout()
plt.savefig("../Results/tabpfn/ablation/ablation_comparison.pdf", bbox_inches="tight")
plt.show()

print("Color legend: Coral=1-group, Blue=2-group, Purple=3-group, Green=Baseline")

# %% [markdown]
# ## Delta Analysis vs Baseline

# %%
baseline_row = summary_df[summary_df["Experiment"] == "baseline_all_features"].iloc[0]
baseline_mae = baseline_row["MAE"]
baseline_pearson = baseline_row["Pearson_R"]

delta_df = summary_df.copy()
delta_df["MAE_Delta"] = (delta_df["MAE"] - baseline_mae).round(3)
delta_df["Pearson_Delta"] = (delta_df["Pearson_R"] - baseline_pearson).round(3)
delta_df["RMSE_Delta"] = (delta_df["RMSE"] - baseline_row["RMSE"]).round(3)
delta_df["R2_Delta"] = (delta_df["R2"] - baseline_row["R2"]).round(3)
delta_df["Spearman_Delta"] = (delta_df["Spearman_R"] - baseline_row["Spearman_R"]).round(3)

print("Delta analysis (positive MAE_Delta = worse than baseline):\n")
print(delta_df[["Experiment", "Combo_Size", "N_Features",
                "MAE", "MAE_Delta", "RMSE", "RMSE_Delta",
                "R2", "R2_Delta", "Pearson_R", "Pearson_Delta",
                "Spearman_R", "Spearman_Delta"]].to_string(index=False))

delta_df.to_csv("../Results/tabpfn/ablation/ablation_delta_analysis.csv", index=False)
print("\nSaved ablation_delta_analysis.csv")

# %%
fig, axes = plt.subplots(1, 2, figsize=(14, max(6, len(delta_df) * 0.3)))
fig.set_dpi(150)
fig.set_facecolor("white")

color_map = {1: "coral", 2: "steelblue", 3: "mediumpurple", 4: "green"}

# MAE Delta plot
ax = axes[0]
delta_sorted = delta_df.sort_values("MAE_Delta", ascending=False)
bar_colors = [color_map.get(k, "gray") for k in delta_sorted["Combo_Size"]]
ax.barh(delta_sorted["Experiment"], delta_sorted["MAE_Delta"], color=bar_colors, alpha=0.8)
ax.set_xlabel("MAE Change vs Baseline")
ax.set_title("MAE Delta (positive = worse than baseline)")
ax.axvline(x=0, color="black", linewidth=0.5)
ax.invert_yaxis()

# Pearson Delta plot
ax = axes[1]
delta_sorted2 = delta_df.sort_values("Pearson_Delta")
bar_colors2 = [color_map.get(k, "gray") for k in delta_sorted2["Combo_Size"]]
ax.barh(delta_sorted2["Experiment"], delta_sorted2["Pearson_Delta"], color=bar_colors2, alpha=0.8)
ax.set_xlabel("Pearson R Change vs Baseline")
ax.set_title("Pearson R Delta (negative = worse than baseline)")
ax.axvline(x=0, color="black", linewidth=0.5)
ax.invert_yaxis()

plt.tight_layout()
plt.savefig("../Results/tabpfn/ablation/ablation_delta_plot.pdf", bbox_inches="tight")
plt.show()

print("Color legend: Coral=1-group, Blue=2-group, Purple=3-group, Green=Baseline")

# %% [markdown]
# ## Performance Distribution by Combination Size

# %%
fig, axes = plt.subplots(1, 3, figsize=(15, 5))
fig.set_dpi(150)
fig.set_facecolor("white")

for ax, metric, title in zip(axes, ["MAE", "Pearson_R", "R2"],
                              ["MAE (lower is better)", "Pearson R (higher is better)", "R-squared (higher is better)"]):
    sn.boxplot(data=summary_df, x="Combo_Size", y=metric, ax=ax,
               palette={1: "coral", 2: "steelblue", 3: "mediumpurple", 4: "green"})
    ax.set_xlabel("Number of Patient Groups")
    ax.set_ylabel(metric)
    ax.set_title(title)

plt.tight_layout()
plt.savefig("../Results/tabpfn/ablation/ablation_boxplot_by_size.pdf", bbox_inches="tight")
plt.show()

# %% [markdown]
# ## Feature Group Importance
#
# Across all experiments, how often does each patient group appear in the top-performing combinations?

# %%
# For each combo size, find the best experiment and count group appearances
# Also rank all experiments by MAE and look at top-N
top_n = 10
top_experiments = summary_df.sort_values("MAE").head(top_n)

print(f"Top {top_n} experiments by MAE:\n")
print(top_experiments[["Experiment", "Combo_Size", "N_Features", "MAE", "Pearson_R"]].to_string(index=False))

# Count group appearances in top experiments
from collections import Counter
group_counter = Counter()
for _, row in top_experiments.iterrows():
    if row["Experiment"] == "baseline_all_features":
        continue
    groups_str = row["Experiment"].split("_", 2)[2]
    for g in groups_str.split("+"):
        group_counter[g] += 1

print(f"\nGroup frequency in top {top_n} experiments:")
for group, count in group_counter.most_common():
    print(f"  {group}: {count}")

# Plot group frequency
fig, ax = plt.subplots(figsize=(8, 4))
fig.set_dpi(150)
fig.set_facecolor("white")
groups_sorted = sorted(group_counter.keys(), key=lambda g: group_counter[g], reverse=True)
counts = [group_counter[g] for g in groups_sorted]
ax.bar(groups_sorted, counts, color="teal", alpha=0.8)
ax.set_ylabel(f"Appearances in Top {top_n}")
ax.set_title(f"Feature Group Frequency in Top {top_n} Experiments (by MAE)")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.savefig("../Results/tabpfn/ablation/ablation_group_importance.pdf", bbox_inches="tight")
plt.show()

# %% [markdown]
# ## Pairwise Group Contribution Heatmap
#
# For 2-group combinations, shows MAE for each pair.

# %%
pair_df = summary_df[summary_df["Combo_Size"] == 2].copy()

if len(pair_df) > 0:
    # Extract group names from experiments
    all_group_names = sorted(set(
        g for _, row in pair_df.iterrows()
        for g in row["Experiment"].split("_", 2)[2].split("+")
    ))

    # Build symmetric matrix
    mae_matrix = pd.DataFrame(np.nan, index=all_group_names, columns=all_group_names)
    pearson_matrix = pd.DataFrame(np.nan, index=all_group_names, columns=all_group_names)

    # Fill diagonal with single-group results
    single_df = summary_df[summary_df["Combo_Size"] == 1]
    for _, row in single_df.iterrows():
        g = row["Experiment"].split("_", 2)[2]
        if g in all_group_names:
            mae_matrix.loc[g, g] = round(row["MAE"], 3)
            pearson_matrix.loc[g, g] = round(row["Pearson_R"], 3)

    # Fill off-diagonal with pair results
    for _, row in pair_df.iterrows():
        groups = row["Experiment"].split("_", 2)[2].split("+")
        g1, g2 = groups[0], groups[1]
        mae_matrix.loc[g1, g2] = round(row["MAE"], 3)
        mae_matrix.loc[g2, g1] = round(row["MAE"], 3)
        pearson_matrix.loc[g1, g2] = round(row["Pearson_R"], 3)
        pearson_matrix.loc[g2, g1] = round(row["Pearson_R"], 3)

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    fig.set_dpi(150)
    fig.set_facecolor("white")

    sn.heatmap(mae_matrix.astype(float), annot=True, fmt=".3f", cmap="YlOrRd_r", ax=axes[0])
    axes[0].set_title("MAE: Single (diagonal) & Pair (off-diagonal)")

    sn.heatmap(pearson_matrix.astype(float), annot=True, fmt=".3f", cmap="YlGn", ax=axes[1])
    axes[1].set_title("Pearson R: Single (diagonal) & Pair (off-diagonal)")

    plt.tight_layout()
    plt.savefig("../Results/tabpfn/ablation/ablation_pair_heatmap.pdf", bbox_inches="tight")
    plt.show()
else:
    print("No 2-group results found.")
